GET http://localhost:2222/productlist


###
POST http://localhost:2222/productlist
Content-Type:application/json

{
    "pname": "Apple23",
    "price": 4000,
    "qty": 300,
    "seller": "aaaaaa"
}


###
GET http://localhost:2222/productlist/6534eb5851f4fcce822f34ba


###
PUT  http://localhost:2222/productlist
Content-Type:application/json

{
    "productid":"653ce527a6d55054a1ffabdf",
    "pname": "Mango2",
    "price": 5800,
    "qty": 503,
    "seller": "Suraj Ku"
}


###
DELETE http://localhost:2222/productlist/6534e95251f4fcce822f34b5
